### ISSUE TITLE
Instance-handling in VSC

### ISSUE THREAD

**Issue by erikbosch** [GENIVI/vehicle_service_catalog#10]
In VSS we have the concept of instances to describe that there are (or might be) multiple instances of a specific branch. As of today, it is necessary to specify the exact range supported.

```
Door:
  type: branch
  instances:
    - Row[1,2]
    - ["Left","Right"]
  description: All doors, including windows and switches
```

Currently in VSC we instead for the seat example methods use explicit parameters to indicate row and index. That might work well for methods but does not work that well for VSC properties.

How do we intend to handle instances in VSC? Do we intend to use something similar to `instances` in VSS, e.g. by adding support in a service specification or a name space specification that there might be multiple instances of this service, possibly like below. I.e. no need to include e.g. seat row/index in method signatures, that can be added during generation if needed. Or do we prefer the method used in the example? If so - how are representation of VSC properties with multipe instances supposed to be handled?

```
namespaces:


  - name: seats
    description: Seat interface and datatypes.
    instances:
          - name: row
            datatype: uint8_t
          - name: index
            datatype: uint8_t

    methods:
      - name: current_position
        description: |
          Get the current position of the seat

        out:
          - name: seat
            description: |
              The seat state that was requested
            datatype: movement.seat_t

```
